[versions]
agp = "8.0.2"
kotlin = "1.8.0"
ksp = "1.8.10-1.0.9"
hilt = "2.47"
hilt-androidx = "1.0.0"
hilt-navigation-compose = "1.0.0"
androidx-kotlin = "1.8.0"

# view
compose = "2022.10.00"
lifecycle = "2.3.1"
activity = "1.6.1"
appcompat = "1.6.1"
material = "1.9.0"
recylerview = "1.2.0"
constraintlayout = "2.0.4"
fragmentktx = "1.6.1"
navigation = "2.5.3"
glide = "4.15.1"
coil = "2.4.0"

retrofit = "2.9.0"
okhttp = "4.10.0"
moshi = "1.14.0"

# test
junit = "4.13.2"

# android test
junit-ext = "1.1.3"
espresso = "3.4.0"
compose-junit = "1.4.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
navigation = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin" }

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "androidx.kotlin" }
material = { module = "com.google.android.material:material", version.ref = "material" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

# androidx
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx.kotlin" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
# androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
# androidx-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

# view
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
recylerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recylerview" }
fragmentktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentktx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

# navigation
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }

# compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material = { module = "androidx.compose.material3:material3" }

# compose: debug
debug-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
debug-compose-ui-test = { module = "androidx.compose.ui:ui-test-manifest" }

# retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

# hilt
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-kapt = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt.navigation.compose" }

# test
junit = { module = "junit:junit", version.ref = "junit" }

# hilt test
hilt-test = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

# android test
junit-ext = { module = "androidx.test.ext:junit", version.ref = "junit.ext" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
atest-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
atest-compose-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose.junit" }